all: list stack equationchecker floodfill

list: testMyTemplate.cpp
	g++ testMyTemplate.cpp -o list_test

stack: testMyStack.cpp
	g++ testMyStack.cpp -o stack_test

equationchecker: equationChecker.cpp
	g++ equationChecker.cpp -o eqchecker

floodfill: flood_fill.cpp
	g++ flood_fill.cpp -o flood_fill
