all: array pointers

array: list_3358_array_test.cpp list_3358_arrays.cpp
	g++ -o array_test list_3358_array_test.cpp list_3358_arrays.cpp

pointers: list_3358_pointers_test.cpp list_3358_pointers.cpp
	g++ -o pointer_test list_3358_pointers_test.cpp list_3358_pointers.cpp